spring:
  datasource:
    url: jdbc:mysql://localhost:3306/naega?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Aa2592256@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true